### ISSUE TITLE
Invalid OTP - doing login

### ISSUE THREAD

**Issue by Fardeen18** [Shoonya-Dev/ShoonyaApi-py#131]
DEBUG:NorenRestApiPy.NorenApi:https://api.shoonya.com/NorenWClientTP//QuickAuth
DEBUG:NorenRestApiPy.NorenApi:Req:jData={"source": "API", "apkversion": "1.0.0", "uid": "FA136941", "pwd": "c75f28325cfa028ea13872f977a29e0e87c99a4f390fe260f24d7e1f05fb8d75", "factor2": "ABIPF6116B", "vc": "FA136941_U", "appkey": "493f2559ed8743d4781ff3be6f185f5f7e7a24e99c87c04b0c581479e1a5cb8d", "imei": "abc1234"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//QuickAuth HTTP/1.1" 200 91
DEBUG:NorenRestApiPy.NorenApi:Reply:{"request_time":"16:30:15 15-08-2023","stat":"Not_Ok","emsg":"Invalid Input : Invalid OTP"}

**Comment by Fardeen18** [comment]
please some one help me on this

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your concern.

**"stat":"Not_Ok","emsg":"Invalid Input : Invalid OTP"}** The Shared Error represents the OTP is invalid which means you have inserted the wrong OTP or TOTP. we request please insert the correct OTP/ TOTP. 
You can get this error in two scenarios; first, you are not putting TOTP inside the time slot of 30 seconds. Secondly, this happens due to the non-sync of the phone and the system, i.e. the time of the system and the phone do not match.

**For your help, Please refer to the API FAQ:-** [](https://shoonya.com/faqs/apis/when-i-try-to-log-in-with-totp-in-shoonya-api,-i-get-an-%22invalid-otp%22-error.-how-to-fix-this-error)

For more help, you can get the raise the email at **apisupport@shoonya.com**

Team Shoonya
